# Cloud Build configuration for GCP deployment

steps:
  # Pull previous image for caching (continue if not found)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/photocat:latest || echo "No cache found, building from scratch"']
    id: 'pull-cache'
  
  # Use Node 20 for Vite 7.x compatibility - clean install + build
  - name: 'node:20'
    entrypoint: 'bash'
    args: ['-c', 'npm ci --include=dev && npm run build']
  
  # Build the container image with BuildKit and cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'PRELOAD_SIGLIP=1',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '--cache-from', 'gcr.io/$PROJECT_ID/photocat:latest',
      '-t', 'gcr.io/$PROJECT_ID/photocat:$_COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/photocat:latest',
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/photocat:$_COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/photocat:latest']
  
  # Deploy to Cloud Run (API service)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'photocat-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/photocat:$_COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=900'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=prod,TAGGING_MODEL=siglip,THUMBNAIL_BUCKET_NAME=photocat-483622-thumbnails,THUMBNAIL_CDN_BASE_URL=https://pc.nedeva.com,DATABASE_URL=postgresql://photocat-user:EcrZH7UymHpa6kqduFHG@/photocat_prod?host=/cloudsql/${_CLOUDSQL_INSTANCE}'
      - '--set-secrets'
      - 'DROPBOX_APP_KEY=dropbox-app-key:latest,DROPBOX_APP_SECRET=dropbox-app-secret:latest'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
  
  # Deploy worker service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'photocat-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/photocat:$_COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=900'
      - '--max-instances=1'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=$PROJECT_ID,ENVIRONMENT=prod,WORKER_MODE=true,TAGGING_MODEL=siglip,THUMBNAIL_BUCKET_NAME=photocat-483622-thumbnails,THUMBNAIL_CDN_BASE_URL=https://pc.nedeva.com,DATABASE_URL=postgresql://photocat-user:EcrZH7UymHpa6kqduFHG@/photocat_prod?host=/cloudsql/${_CLOUDSQL_INSTANCE}'
      - '--set-secrets'
      - 'DROPBOX_APP_KEY=dropbox-app-key:latest,DROPBOX_APP_SECRET=dropbox-app-secret:latest'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'

images:
  - 'gcr.io/$PROJECT_ID/photocat:$_COMMIT_SHA'

substitutions:
  _CLOUDSQL_INSTANCE: 'photocat-483622:us-central1:photocat-db'

options:
  machineType: 'E2_MEDIUM'

timeout: '2400s'  # 40 minutes
