# Cloud Build configuration for GCP deployment

steps:
  # Pull previous image for caching (continue if not found)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/zoltag:latest || echo "No cache found, building from scratch"']
    id: 'pull-cache'
  
  # Use Node 20 for Vite 7.x compatibility - clean install + build
  - name: 'node:20'
    entrypoint: 'bash'
    args: ['-c', 'export VITE_SUPABASE_URL=$$SUPABASE_URL && export VITE_SUPABASE_ANON_KEY=$$SUPABASE_ANON_KEY && npm ci --include=dev && npm run build']
    secretEnv:
      - 'SUPABASE_URL'
      - 'SUPABASE_ANON_KEY'
  
  # Build the container image with BuildKit and cache
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'PRELOAD_SIGLIP=0',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '--cache-from', 'gcr.io/$PROJECT_ID/zoltag:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/photocat:model-cache',
      '-t', 'gcr.io/$PROJECT_ID/zoltag:$_COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/zoltag:latest',
      '.'
    ]
    env:
      - 'DOCKER_BUILDKIT=1'
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zoltag:$_COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zoltag:latest']
  
  # Deploy to Cloud Run (API service)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zoltag-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zoltag:$_COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=1'
      - '--timeout=900'
      - '--max-instances=1'
      - '--min-instances=0'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=photocat-483622,ENVIRONMENT=prod,APP_URL=https://zoltag.com,TAGGING_MODEL=siglip,STORAGE_BUCKET_NAME=photocat-483622-prod-shared,THUMBNAIL_BUCKET_NAME=photocat-483622-prod-shared,PERSON_REFERENCE_BUCKET_NAME=photocat-483622-prod-person-references,THUMBNAIL_CDN_BASE_URL=,THUMBNAIL_SIGNED_URLS=true,GEMINI_API_MODE=vertex,GEMINI_MODEL=gemini-2.5-flash-lite,DB_POOL_SIZE=8,DB_MAX_OVERFLOW=4,DB_POOL_TIMEOUT=15,DB_POOL_RECYCLE=300,DB_CONNECT_TIMEOUT=10,DB_POOL_USE_LIFO=true,DB_KEEPALIVES=1,DB_KEEPALIVES_IDLE=30,DB_KEEPALIVES_INTERVAL=10,DB_KEEPALIVES_COUNT=5,UPLOAD_GENERATE_EMBEDDINGS=false'
      - '--set-secrets'
      - 'DROPBOX_APP_KEY=dropbox-app-key:latest,DROPBOX_APP_SECRET=dropbox-app-secret:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest,DATABASE_URL=supabase-db-url:latest,GEMINI_API_KEY=gemini-api-key:latest,EMAIL_RESEND_API_KEY=email-resend-api-key:latest'

  # Deploy worker service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zoltag-worker'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zoltag:$_COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=900'
      - '--max-instances=1'
      - '--set-env-vars'
      - 'GCP_PROJECT_ID=photocat-483622,ENVIRONMENT=prod,WORKER_MODE=true,TAGGING_MODEL=siglip,STORAGE_BUCKET_NAME=photocat-483622-prod-shared,THUMBNAIL_BUCKET_NAME=photocat-483622-prod-shared,PERSON_REFERENCE_BUCKET_NAME=photocat-483622-prod-person-references,THUMBNAIL_CDN_BASE_URL=https://storage.googleapis.com/photocat-483622-prod-shared,GEMINI_API_MODE=vertex,GEMINI_MODEL=gemini-2.5-flash-lite,DB_POOL_SIZE=4,DB_MAX_OVERFLOW=2,DB_POOL_TIMEOUT=15,DB_POOL_RECYCLE=300,DB_CONNECT_TIMEOUT=10,DB_POOL_USE_LIFO=true,DB_KEEPALIVES=1,DB_KEEPALIVES_IDLE=30,DB_KEEPALIVES_INTERVAL=10,DB_KEEPALIVES_COUNT=5'
      - '--set-secrets'
      - 'DROPBOX_APP_KEY=dropbox-app-key:latest,DROPBOX_APP_SECRET=dropbox-app-secret:latest,SUPABASE_SERVICE_ROLE_KEY=supabase-service-role-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest,DATABASE_URL=supabase-db-url:latest,GEMINI_API_KEY=gemini-api-key:latest,EMAIL_RESEND_API_KEY=email-resend-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/zoltag:$_COMMIT_SHA'

options:
  machineType: 'E2_MEDIUM'

timeout: '2400s'  # 40 minutes

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/supabase-url/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/supabase-anon-key/versions/latest
      env: 'SUPABASE_ANON_KEY'
