
"""Initial schema

Revision ID: 7c78a8bd4b5f
Revises: 
Create Date: 2026-01-07 17:48:00.885862
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision = '7c78a8bd4b5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dropbox_cursors',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('cursor', sa.Text(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('image_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('dropbox_path', sa.String(length=1024), nullable=False),
    sa.Column('dropbox_id', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('modified_time', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('perceptual_hash', sa.String(length=64), nullable=True),
    sa.Column('color_histogram', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('exif_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('camera_make', sa.String(length=255), nullable=True),
    sa.Column('camera_model', sa.String(length=255), nullable=True),
    sa.Column('lens_model', sa.String(length=255), nullable=True),
    sa.Column('iso', sa.Integer(), nullable=True),
    sa.Column('aperture', sa.Float(), nullable=True),
    sa.Column('shutter_speed', sa.String(length=50), nullable=True),
    sa.Column('focal_length', sa.Float(), nullable=True),
    sa.Column('capture_timestamp', sa.DateTime(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('last_processed', sa.DateTime(), nullable=True),
    sa.Column('processing_version', sa.String(length=50), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=1024), nullable=True),
    sa.Column('embedding_generated', sa.Boolean(), nullable=True),
    sa.Column('faces_detected', sa.Boolean(), nullable=True),
    sa.Column('tags_applied', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_capture', 'image_metadata', ['tenant_id', 'capture_timestamp'], unique=False)
    op.create_index('idx_tenant_location', 'image_metadata', ['tenant_id', 'gps_latitude', 'gps_longitude'], unique=False)
    op.create_index('idx_tenant_modified', 'image_metadata', ['tenant_id', 'modified_time'], unique=False)
    op.create_index(op.f('ix_image_metadata_capture_timestamp'), 'image_metadata', ['capture_timestamp'], unique=False)
    op.create_index(op.f('ix_image_metadata_content_hash'), 'image_metadata', ['content_hash'], unique=False)
    op.create_index(op.f('ix_image_metadata_dropbox_id'), 'image_metadata', ['dropbox_id'], unique=True)
    op.create_index(op.f('ix_image_metadata_perceptual_hash'), 'image_metadata', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_image_metadata_tenant_id'), 'image_metadata', ['tenant_id'], unique=False)
    op.create_table('detected_faces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('person_name', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox_top', sa.Integer(), nullable=True),
    sa.Column('bbox_right', sa.Integer(), nullable=True),
    sa.Column('bbox_bottom', sa.Integer(), nullable=True),
    sa.Column('bbox_left', sa.Integer(), nullable=True),
    sa.Column('face_encoding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_person', 'detected_faces', ['tenant_id', 'person_name'], unique=False)
    op.create_index(op.f('ix_detected_faces_person_name'), 'detected_faces', ['person_name'], unique=False)
    op.create_index(op.f('ix_detected_faces_tenant_id'), 'detected_faces', ['tenant_id'], unique=False)
    op.create_table('image_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('embedding', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_id')
    )
    op.create_index(op.f('ix_image_embeddings_tenant_id'), 'image_embeddings', ['tenant_id'], unique=False)
    op.create_table('image_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('manual', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_metadata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_keyword', 'image_tags', ['tenant_id', 'keyword'], unique=False)
    op.create_index(op.f('ix_image_tags_keyword'), 'image_tags', ['keyword'], unique=False)
    op.create_index(op.f('ix_image_tags_tenant_id'), 'image_tags', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_tags_tenant_id'), table_name='image_tags')
    op.drop_index(op.f('ix_image_tags_keyword'), table_name='image_tags')
    op.drop_index('idx_tenant_keyword', table_name='image_tags')
    op.drop_table('image_tags')
    op.drop_index(op.f('ix_image_embeddings_tenant_id'), table_name='image_embeddings')
    op.drop_table('image_embeddings')
    op.drop_index(op.f('ix_detected_faces_tenant_id'), table_name='detected_faces')
    op.drop_index(op.f('ix_detected_faces_person_name'), table_name='detected_faces')
    op.drop_index('idx_tenant_person', table_name='detected_faces')
    op.drop_table('detected_faces')
    op.drop_index(op.f('ix_image_metadata_tenant_id'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_perceptual_hash'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_dropbox_id'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_content_hash'), table_name='image_metadata')
    op.drop_index(op.f('ix_image_metadata_capture_timestamp'), table_name='image_metadata')
    op.drop_index('idx_tenant_modified', table_name='image_metadata')
    op.drop_index('idx_tenant_location', table_name='image_metadata')
    op.drop_index('idx_tenant_capture', table_name='image_metadata')
    op.drop_table('image_metadata')
    op.drop_table('dropbox_cursors')
    # ### end Alembic commands ###
